docker pull gcr.io/google-samples/microservices-demo/adservice:v0.3.6
docker pull gcr.io/google-samples/microservices-demo/cartservice:v0.3.6
docker pull gcr.io/google-samples/microservices-demo/checkoutservice:v0.3.6
docker pull gcr.io/google-samples/microservices-demo/currencyservice:v0.3.6
docker pull gcr.io/google-samples/microservices-demo/emailservice:v0.3.6
docker pull gcr.io/google-samples/microservices-demo/frontendservice:v0.3.6
docker pull prom/prometheus:v2.33.3
docker pull gcr.io/google-samples/microservices-demo/paymentservice:v0.3.6
docker pull gcr.io/google-samples/microservices-demo/productcatalogservice:v0.3.6
docker pull gcr.io/google-samples/microservices-demo/recommendationservice:v0.3.6
docker pull gcr.io/google-samples/microservices-demo/shippingservice:v0.3.6