apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.24.0
          args:
            - "--config.file=/opt/alertmanager/alertmanager.yml"
            - "--storage.path=/opt/alertmanager/data"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9093
          volumeMounts:
            - name: alertmanager-config-volume
              mountPath: /opt/alertmanager
            - name: data-volume
              mountPath: /opt/alertmanager/data
      volumes:
        - name: alertmanager-config-volume
          configMap:
            defaultMode: 420
            name: alertmanager-conf
        - name: data-volume
          emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-conf
  labels:
    name: alertmanager-conf
data:
  alertmanager.yml: |-
    route:
      receiver: admin

    receivers:
    - name: admin
      email_configs:
      - to: 'orenbeworldwide@gmail.com'
        from: 'orenbeworldwide@gmail.com'
        smarthost: smtp.gmail.com:587
        auth_username: 'orenbeworldwide@gmail.com'
        auth_identity: 'orenbeworldwide@gmail.com'
        auth_password: 'gfqerozueoqizrej'
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
spec:
  selector:
    app: alertmanager
  ports:
    - port: 9093
      targetPort: 9093
      protocol: TCP
  type: LoadBalancer