---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
        - name: service
          # image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.3.6
          image: docker.io/0908887875/productcatalogservice:v1.0
          resources:
            limits:
              memory: '64Mi'
              cpu: '250m'
          ports:
            - containerPort: 3550
              name: grpc
            - containerPort: 3551
              name: http
          env:
            - name: PORT
              value: '3550'
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
spec:
  selector:
    app: productcatalogservice
  ports:
    - name: grpc
      protocol: TCP
      port: 3550
      targetPort: 3550
    - name: http
      protocol: TCP
      port: 3551
      targetPort: 3551
