---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
spec:
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
        - name: service
          # image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.3.6
          image: 0908887875/recommendationservice:v1.0
          resources:
            limits:
              memory: '64Mi'
              cpu: '250m'
          ports:
            - containerPort: 8080
              name: grpc
            - containerPort: 8081
              name: http
          env:
            - name: PORT
              value: '8080'
            - name: DISABLE_TRACING
              value: '1'
            - name: DISABLE_PROFILER
              value: '1'
            - name: DISABLE_DEBUGGER
              value: '1'
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: 'productcatalogservice:3550'
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
spec:
  selector:
    app: recommendationservice
  ports:
    - name: grpc
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
